# The number of replicas to deploy for the application
replicaCount: 1

# Configuration specific to terralist application
terralistConfig: {}
  #TERRALIST_URL: https://terralist.example.com

# Configuration Secrets specific to terralist application
terralistSecrets: {}

# Image configurations
image:
  repository: ghcr.io/terralist/terralist  # Docker image repository
  pullPolicy: Always  # Image pull policy (Always, IfNotPresent, Never)

# List of image pull secrets for private repositories
imagePullSecrets: []
#   - name: private-docker-reg-secret

# Overrides for chart name (helpful when you want to change the default resource names)
nameOverride: ""
fullnameOverride: ""

# Service configurations
service:
  type: ClusterIP  # Kubernetes Service type
  port: 80  # Service port exposed externally
  targetPort: 5758  # Container port to which the service will send traffic

# Service account configurations
serviceAccount:
  enabled: false  # Specifies whether a service account should be created
  annotations: {}

# Ingress configurations
ingress:
  enabled: false  # Enable or disable Ingress
  className: "nginx"
  annotations: {}
  hosts: []
  tls: []

# Resources requests and limits
resources: {}
  # limits:
  #   cpu: "1"
  #   memory: "512Mi"
  # requests:
  #   cpu: "500m"
  #   memory: "256Mi"

# Annotations to add to the pod
podAnnotations: {}

# Security context for the pod
securityContext: {}

# Security context for all containers in the pod
podSecurityContext: {}

# Rolling update strategy
rollingUpdate:
  maxSurge: 1       # The maximum number of pods that can be created over the desired number of pods
  maxUnavailable: 1 # The maximum number of pods that can be unavailable during the update process

affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #           - key: app.kubernetes.io/name
  #             operator: In
  #             values:
  #               - terralist
  #       topologyKey: "kubernetes.io/hostname"

# Node selector for pod scheduling
nodeSelector: {}

# Tolerations for pod scheduling
tolerations: []

# Probes for checking the health of the application
probes:
  readinessProbe:
    enabled: true
    path: /check/healthz
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    enabled: true
    path: /check/healthz
    initialDelaySeconds: 15
    periodSeconds: 20
  startupProbe:
    enabled: true
    path: /check/healthz
    initialDelaySeconds: 10
    periodSeconds: 5

# Pod Disruption Budget (PDB) settings
Pdb:
  enabled: false
  minAvailable: 1  # Minimum available instances during a voluntary disruption
  maxUnavailable: null  # Optionally set the maximum unavailable instances

# Horizontal Pod Autoscaler (HPA) configurations
hpa:
  enabled: false # Enable or disable HPA
  targetCPUUtilizationPercentage: 80  # Target CPU utilization percentage for HPA to trigger scaling
  maxReplicas: 10  # Maximum number of pods that HPA can scale up to
  minReplicas: 2  # Minimum number of pods that HPA should maintain