{{- if .Values.terralistSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terralist.fullname" . }}
  labels:
    {{- include "terralist.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.terralistSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}